package com.tychees.core.constants;

import org.springframework.stereotype.Component;

@Component
public class SettingsConstants 
	implements java.io.Serializable
{
    private final static long serialVersionUID = 1467880004586236216L;
    
	public SettingsConstants() {}
	
    // SETTINGS Key: POS
    public final String SETTINGS_POS_KEY_GENERAL_ITEMVIEW_TYPE                  = "PLACE_SETTINGS_POS_KEY_GENERAL_ITEMVIEW_TYPE";
    public final String SETTINGS_POS_KEY_GENERAL_CURRENCY                       = "PLACE_SETTINGS_POS_KEY_GENERAL_CURRENCY";
    public final String SETTINGS_POS_KEY_GENERAL_ROUND_TO_MULTIPLE_FIVE         = "PLACE_SETTINGS_POS_KEY_GENERAL_ROUND_TO_MULTIPLE_FIVE";
    
    public final String SETTINGS_POS_KEY_GST_ENABLED                            = "PLACE_SETTINGS_POS_KEY_GST_ENABLED";
    public final String SETTINGS_POS_KEY_GST_TAX_INVOICE_NUMBER                 = "PLACE_SETTINGS_POS_KEY_GST_TAX_INVOICE_NUMBER";

    public final String SETTINGS_POS_KEY_QUOTATION_ENABLED                      = "PLACE_SETTINGS_POS_KEY_QUOTATION_ENABLED";
    public final String SETTINGS_POS_KEY_QUOTATION_TEMPLATE                     = "PLACE_SETTINGS_POS_KEY_QUOTATION_TEMPLATE";
    public final String SETTINGS_POS_KEY_QUOTATION_NO_PREFIX                    = "PLACE_SETTINGS_POS_KEY_QUOTATION_NO_PREFIX";
    public final String SETTINGS_POS_KEY_QUOTATION_NO_MAX                       = "PLACE_SETTINGS_POS_KEY_QUOTATION_NO_MAX";
    public final String SETTINGS_POS_KEY_QUOTATION_NO_NEXT                      = "PLACE_SETTINGS_POS_KEY_QUOTATION_NO_NEXT";

    public final String SETTINGS_POS_KEY_BILLING_ENABLED                        = "PLACE_SETTINGS_POS_KEY_BILLING_ENABLED";
    public final String SETTINGS_POS_KEY_BILLING_FULL_TEMPLATE                  = "PLACE_SETTINGS_POS_KEY_BILLING_FULL_TEMPLATE";
    public final String SETTINGS_POS_KEY_BILLING_NO_PREFIX                      = "PLACE_SETTINGS_POS_KEY_BILLING_NO_PREFIX";
    public final String SETTINGS_POS_KEY_BILLING_NO_MAX                         = "PLACE_SETTINGS_POS_KEY_BILLING_NO_MAX";
    public final String SETTINGS_POS_KEY_BILLING_NO_NEXT                        = "PLACE_SETTINGS_POS_KEY_BILLING_NO_NEXT";

    public final String SETTINGS_POS_KEY_SALES_INVOICE_ENABLED                  = "PLACE_SETTINGS_POS_KEY_SALES_INVOICE_ENABLED";
    public final String SETTINGS_POS_KEY_SALES_INVOICE_TEMPLATE                 = "PLACE_SETTINGS_POS_KEY_SALES_INVOICE_TEMPLATE";

    public final String SETTINGS_POS_KEY_TAX_INVOICE_ENABLED                    = "PLACE_SETTINGS_POS_KEY_TAX_INVOICE_ENABLED";
    public final String SETTINGS_POS_KEY_TAX_INVOICE_TEMPLATE                   = "PLACE_SETTINGS_POS_KEY_TAX_INVOICE_TEMPLATE";
    public final String SETTINGS_POS_KEY_TAX_INVOICE_NO_PREFIX                  = "PLACE_SETTINGS_POS_KEY_TAX_INVOICE_NO_PREFIX";
    public final String SETTINGS_POS_KEY_TAX_INVOICE_NO_MAX                     = "PLACE_SETTINGS_POS_KEY_TAX_INVOICE_NO_MAX";
    public final String SETTINGS_POS_KEY_TAX_INVOICE_NO_NEXT                    = "PLACE_SETTINGS_POS_KEY_TAX_INVOICE_NO_NEXT";

    public final String SETTINGS_POS_KEY_PAYMENT_RECEIPT_ENABLED                = "PLACE_SETTINGS_POS_KEY_PAYMENT_RECEIPT_ENABLED";
    public final String SETTINGS_POS_KEY_PAYMENT_RECEIPT_TEMPLATE               = "PLACE_SETTINGS_POS_KEY_PAYMENT_RECEIPT_TEMPLATE";
    public final String SETTINGS_POS_KEY_PAYMENT_RECEIPT_NO_PREFIX              = "PLACE_SETTINGS_POS_KEY_PAYMENT_RECEIPT_NO_PREFIX";
    public final String SETTINGS_POS_KEY_PAYMENT_RECEIPT_NO_MAX                 = "PLACE_SETTINGS_POS_KEY_PAYMENT_RECEIPT_NO_MAX";
    public final String SETTINGS_POS_KEY_PAYMENT_RECEIPT_NO_NEXT                = "PLACE_SETTINGS_POS_KEY_PAYMENT_RECEIPT_NO_NEXT";

    public final String SETTINGS_POS_KEY_PAYMENT_VOUCHER_ENABLED                = "PLACE_SETTINGS_POS_KEY_PAYMENT_VOUCHER_ENABLED";
    public final String SETTINGS_POS_KEY_PAYMENT_VOUCHER_TEMPLATE               = "PLACE_SETTINGS_POS_KEY_PAYMENT_VOUCHER_TEMPLATE";
    public final String SETTINGS_POS_KEY_PAYMENT_VOUCHER_NO_PREFIX              = "PLACE_SETTINGS_POS_KEY_PAYMENT_VOUCHER_NO_PREFIX";
    public final String SETTINGS_POS_KEY_PAYMENT_VOUCHER_NO_MAX                 = "PLACE_SETTINGS_POS_KEY_PAYMENT_VOUCHER_NO_MAX";
    public final String SETTINGS_POS_KEY_PAYMENT_VOUCHER_NO_NEXT                = "PLACE_SETTINGS_POS_KEY_PAYMENT_VOUCHER_NO_NEXT";

    public final String SETTINGS_POS_KEY_DELIVERY_ORDER_ENABLED                 = "PLACE_SETTINGS_POS_KEY_DELIVERY_ORDER_ENABLED";
    public final String SETTINGS_POS_KEY_DELIVERY_ORDER_TEMPLATE                = "PLACE_SETTINGS_POS_KEY_DELIVERY_ORDER_TEMPLATE";
    public final String SETTINGS_POS_KEY_DELIVERY_ORDER_NO_PREFIX               = "PLACE_SETTINGS_POS_KEY_DELIVERY_ORDER_NO_PREFIX";
    public final String SETTINGS_POS_KEY_DELIVERY_ORDER_NO_MAX                  = "PLACE_SETTINGS_POS_KEY_DELIVERY_ORDER_NO_MAX";
    public final String SETTINGS_POS_KEY_DELIVERY_ORDER_NO_NEXT                 = "PLACE_SETTINGS_POS_KEY_DELIVERY_ORDER_NO_NEXT";

    public final String SETTINGS_POS_KEY_FOOD_ORDER_ENABLED                     = "PLACE_SETTINGS_POS_KEY_FOOD_ORDER_ENABLED";
    public final String SETTINGS_POS_KEY_FOOD_ORDER_TEMPLATE                    = "PLACE_SETTINGS_POS_KEY_FOOD_ORDER_TEMPLATE";
    public final String SETTINGS_POS_KEY_FOOD_ORDER_LABEL                       = "PLACE_SETTINGS_POS_KEY_FOOD_ORDER_LABEL";
    public final String SETTINGS_POS_KEY_DRINK_ORDER_ENABLED                    = "PLACE_SETTINGS_POS_KEY_DRINK_ORDER_ENABLED";
    public final String SETTINGS_POS_KEY_DRINK_ORDER_TEMPLATE                   = "PLACE_SETTINGS_POS_KEY_DRINK_ORDER_TEMPLATE";
    public final String SETTINGS_POS_KEY_DRINK_ORDER_LABEL                      = "PLACE_SETTINGS_POS_KEY_DRINK_ORDER_LABEL";

    public final String SETTINGS_POS_KEY_PAYMENT_DEFAULT_OPTION                 = "PLACE_SETTINGS_POS_KEY_PAYMENT_DEFAULT_OPTION";
    public final String SETTINGS_POS_KEY_PAYMENT_OPTION_CASH_ENABLED            = "PLACE_SETTINGS_POS_KEY_PAYMENT_OPTION_CASH_ENABLED";
    public final String SETTINGS_POS_KEY_PAYMENT_OPTION_CREDIT_CARD_ENABLED     = "PLACE_SETTINGS_POS_KEY_PAYMENT_OPTION_CREDIT_CARD_ENABLED";
    public final String SETTINGS_POS_KEY_PAYMENT_OPTION_CHEQUE_ENABLED          = "PLACE_SETTINGS_POS_KEY_PAYMENT_OPTION_CHEQUE_ENABLED";
    public final String SETTINGS_POS_KEY_PAYMENT_CHEQUE_INFO_REQUIRED           = "PLACE_SETTINGS_POS_KEY_PAYMENT_CHEQUE_INFO_REQUIRED";
    public final String SETTINGS_POS_KEY_PAYMENT_CREDIT_CARD_INFO_REQUIRED      = "PLACE_SETTINGS_POS_KEY_PAYMENT_CREDIT_CARD_INFO_REQUIRED";
    public final String SETTINGS_POS_KEY_PAYMENT_CREDIT_CARD_TYPE      		    = "PLACE_SETTINGS_POS_KEY_PAYMENT_CREDIT_CARD_TYPE";
    
    public final String SETTINGS_POS_KEY_COL_GENDER                             = "PLACE_SETTINGS_POS_KEY_COL_GENDER";
    public final String SETTINGS_POS_KEY_COL_EMAIL                              = "PLACE_SETTINGS_POS_KEY_COL_EMAIL";
    public final String SETTINGS_POS_KEY_COL_CONTACT                            = "PLACE_SETTINGS_POS_KEY_COL_CONTACT";
    public final String SETTINGS_POS_KEY_COL_DOB                                = "PLACE_SETTINGS_POS_KEY_COL_DOB";
    public final String SETTINGS_POS_KEY_COL_LAST_BILLING                       = "PLACE_SETTINGS_POS_KEY_COL_LAST_BILLING";
    
    public final String SETTINGS_POS_KEY_COL_INVOICE_NUMBER                     = "PLACE_SETTINGS_POS_KEY_COL_INVOICE_NUMBER";
    public final String SETTINGS_POS_KEY_COL_DATE_TIME                          = "PLACE_SETTINGS_POS_KEY_COL_DATE_TIME";
    public final String SETTINGS_POS_KEY_COL_CUSTOMER                           = "PLACE_SETTINGS_POS_KEY_COL_CUSTOMER";
    public final String SETTINGS_POS_KEY_COL_TOTAL_AMOUNT                       = "PLACE_SETTINGS_POS_KEY_COL_TOTAL_AMOUNT";
    public final String SETTINGS_POS_KEY_COL_TOTAL_PAYMENT                      = "PLACE_SETTINGS_POS_KEY_COL_TOTAL_PAYMENT";
    
    // SETTINGS Value - POS
    public final String SETTINGS_POS_VALUE_GENERAL_ITEMVIEW_LIST                = "List View";
    public final String SETTINGS_POS_VALUE_GENERAL_BLOCKVIEW_LIST               = "Mansory View";
    
    public final String SETTINGS_POS_VALUE_GENERAL_CURRENCY_MYR                 = "MYR";
    public final String SETTINGS_POS_VALUE_GENERAL_CURRENCY_SGD                 = "SGD";
    
    public final String SETTINGS_POS_VALUE_PAYMENT_CREDIT_CARD_TYPE_VISA		= "Visa";
    public final String SETTINGS_POS_VALUE_PAYMENT_CREDIT_CARD_TYPE_MASTER		= "Master";
    public final String SETTINGS_POS_VALUE_PAYMENT_CREDIT_CARD_TYPE_AMEX		= "Amex";
    public final String SETTINGS_POS_VALUE_PAYMENT_CREDIT_CARD_TYPE_DINERS		= "Diners Club";
    public final String SETTINGS_POS_VALUE_PAYMENT_CREDIT_CARD_TYPE_JCB			= "JCB";
    public final String SETTINGS_POS_VALUE_PAYMENT_CREDIT_CARD_TYPE_DISCOVER	= "Discover";
    public final String SETTINGS_POS_VALUE_PAYMENT_CREDIT_CARD_TYPE_MYDEBIT  	= "MyDebit";
    
    // SETTINGS Key - RELATION
    public final String SETTINGS_RELATION_KEY_CUSTOMER_NO_PREFIX                = "PLACE_SETTINGS_RELATION_KEY_CUSTOMER_NO_PREFIX";
    public final String SETTINGS_RELATION_KEY_CUSTOMER_NO_MAX                   = "PLACE_SETTINGS_RELATION_KEY_CUSTOMER_NO_MAX";
    public final String SETTINGS_RELATION_KEY_CUSTOMER_NO_NEXT                  = "PLACE_SETTINGS_RELATION_KEY_CUSTOMER_NO_NEXT";
    public final String SETTINGS_RELATION_KEY_EMPLOYEE_NO_PREFIX                = "PLACE_SETTINGS_RELATION_KEY_EMPLOYEE_NO_PREFIX";
    public final String SETTINGS_RELATION_KEY_EMPLOYEE_NO_MAX                   = "PLACE_SETTINGS_RELATION_KEY_EMPLOYEE_NO_MAX";
    public final String SETTINGS_RELATION_KEY_EMPLOYEE_NO_NEXT                  = "PLACE_SETTINGS_RELATION_KEY_EMPLOYEE_NO_NEXT";


    // SETTINGS Key - INVENTORY
    public final String SETTINGS_INVENTORY_KEY_SHOW_RAW_CATEGORY			    = "PLACE_SETTINGS_INVENTORY_KEY_SHOW_RAW_CATEGORY";
    public final String SETTINGS_INVENTORY_KEY_SHOW_PRODUCT_CATEGORY		    = "PLACE_SETTINGS_INVENTORY_KEY_SHOW_PRODUCT_CATEGORY";
    public final String SETTINGS_INVENTORY_KEY_SHOW_SERVICE_CATEGORY		    = "PLACE_SETTINGS_INVENTORY_KEY_SHOW_SERVICE_CATEGORY";
    public final String SETTINGS_INVENTORY_KEY_SHOW_EVENT_CATEGORY		        = "PLACE_SETTINGS_INVENTORY_KEY_SHOW_EVENT_CATEGORY";
    public final String SETTINGS_INVENTORY_KEY_SHOW_DISCOUNT_CATEGORY		    = "PLACE_SETTINGS_INVENTORY_KEY_SHOW_DISCOUNT_CATEGORY";
    public final String SETTINGS_INVENTORY_KEY_SHOW_TAX_CATEGORY			    = "PLACE_SETTINGS_INVENTORY_KEY_SHOW_TAX_CATEGORY";
}
